### ISSUE TITLE
OpenShift: Add requirements.txt for Python dependency isolation

### ISSUE THREAD

**Issue by rlaurika** [CSCfi/pouta-ansible-cluster#74]
Currently the Python dependencies for the playbooks for installing OpenShift are documented in README.md. This is OK for manual deployment, but for automated builds in a test pipeline it would be better to explicitly list all Python requirements in a requirements.txt file so that a known fresh Python virtualenv can always be created when running the playbooks. This eliminates errors that happen due to an upgrade in a Python package that the playbooks depend on.

**Comment by tourunen** [comment]
Fixed with #77
