### ISSUE TITLE
OpenStack command line tool has changed

### ISSUE THREAD

**Issue by Jyrsa** [CSCfi/pouta-ansible-cluster#90]
This test https://github.com/CSCfi/pouta-ansible-cluster/blob/master/playbooks/openshift/heat_provision.yml#L13 no longer works on openstack  3.9.0

Instead I get an error about an invalid command
```
$ openstack stack show cluster_name
   openstack: 'stack show cluster_name' is not an openstack command. See 'openstack --help'.
   Did you mean one of these?
   backup create
   backup delete
   backup list
   backup restore
   backup show
$ openstack --version
openstack 3.9.0

```

**Comment by tourunen** [comment]
Check that you have heat client installed in your virtuelenv. See the requirements.txt for dependencies

**Comment by Jyrsa** [comment]
OK. So this particular command requires python-heatclient as well so it was a non-obvious dependency requirement and not changed behaviour between versions.
